workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: توليد الهيكل سحابياً
        script: |
          flutter create --org net.drasty --template=app .
          flutter pub get
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
